services:
  db:
    image: imresamu/postgis:16-3.4
    container_name: postgis_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sjavargata20
      POSTGRES_DB: spatial_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-postgis.sql:/docker-entrypoint-initdb.d/init-postgis.sql
    shm_size: 1g

volumes:
  pgdata: