services:
  db:
    image: imresamu/postgis:16-3.4
    container_name: postgis_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-postgis.sql:/docker-entrypoint-initdb.d/init-postgis.sql:ro
    shm_size: 1g
    networks:
      - adsb_net

volumes:
  pgdata:

networks:
  adsb_net:
    external: true